services:
  db:
    image: mariadb:latest
    container_name: argenchemical_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: argenchemical_db
      MYSQL_USER: fideo
      MYSQL_PASSWORD: 20607154
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - wp_network

  redis:                          
    image: redis:alpine
    container_name: argenchemical_redis
    restart: always
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - ./redis_data:/data        
    networks:
      - wp_network

  wordpress:
    user: "1000:33"
    depends_on:
      - db
      - redis                     
    build:
      context: .
      dockerfile: Dockerfile
    container_name: argenchemical_app
    restart: always
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: fideo
      WORDPRESS_DB_PASSWORD: 20607154
      WORDPRESS_DB_NAME: argenchemical_db
      WORDPRESS_REDIS_HOST: redis  
      WORDPRESS_REDIS_PORT: 6379   
    extra_hosts:
      - "argenchemical.federicomazzei.com.ar:host-gateway"
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wp_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: argenchemical_pma
    restart: always
    depends_on:
      - db
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: fideo
      PMA_PASSWORD: 20607154
      UPLOAD_LIMIT: 300M
    networks:
      - wp_network

networks:
  wp_network:
    driver: bridge
